name: ezy_course_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  dio: ^5.7.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_fonts: ^6.2.1

  intl: ^0.20.1
  json_annotation: ^4.9.0
  readmore: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
