// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserImpl _$$UserImplFromJson(Map<String, dynamic> json) => _$UserImpl(
      id: (json['id'] as num?)?.toInt(),
      schoolId: (json['school_id'] as num?)?.toInt(),
      canWriteDoc: (json['can_write_doc'] as num?)?.toInt(),
      fullName: json['full_name'] as String?,
      isVerified: json['is_verified'] as String?,
      isApproved: (json['is_approved'] as num?)?.toInt(),
      userType: json['user_type'] as String?,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
      isPrivateChat: (json['is_private_chat'] as num?)?.toInt(),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
      profilePic: json['profile_pic'] as String?,
      isOnline: json['is_online'] as String?,
      bio: json['bio'],
      userId: json['user_id'],
      socialAuthProvider: json['social_auth_provider'],
      lastLogin: json['last_login'] == null
          ? null
          : DateTime.parse(json['last_login'] as String),
      status: json['status'],
      isSuspended: (json['is_suspended'] as num?)?.toInt(),
      pauseDate: json['pause_date'],
      expireDate: json['expire_date'],
      lastName: json['last_name'] as String?,
      orderId: json['order_id'],
      firstName: json['first_name'] as String?,
      customFields: json['custom_fields'],
      isAllowChat: json['is_allow_chat'],
      refId: json['ref_id'],
      refCommissionLevel1: (json['ref_commission_level_1'] as num?)?.toInt(),
      refIsCookieDestroyAfterCheckout:
          (json['ref_is_cookie_destroy_after_checkout'] as num?)?.toInt(),
      refCommissionLevel2: (json['ref_commission_level_2'] as num?)?.toInt(),
      parentRefId: json['parent_ref_id'],
      refComL1ValueType: json['ref_com_l1_value_type'] as String?,
      refComL2ValueType: json['ref_com_l2_value_type'] as String?,
      refAllowLinkedMembership:
          (json['ref_allow_linked_membership'] as num?)?.toInt(),
      isManual: (json['is_manual'] as num?)?.toInt(),
      referredBy: json['referred_by'],
      isEligibleForSpecialOffer:
          (json['is_eligible_for_special_offer'] as num?)?.toInt(),
      isFounding: json['is_founding'],
      planId: json['plan_id'],
      is2faEnabled: (json['is_2fa_enabled'] as num?)?.toInt(),
      webpushsub: json['webpushsub'],
      isForceLogoutEnabled: (json['is_force_logout_enabled'] as num?)?.toInt(),
      payoutPaypalEmail: json['payout_paypal_email'],
      refPhyCommissionLevel1:
          (json['ref_phy_commission_level_1'] as num?)?.toInt(),
      isManualPrivateChat: (json['is_manual_private_chat'] as num?)?.toInt(),
      refPhyComL1ValueType: json['ref_phy_com_l1_value_type'] as String?,
      siteOwnerUserId: json['site_owner_user_id'],
      ezyAffiliateUserId: json['ezy_affiliate_user_id'],
      stripePayoutEnabled: (json['stripe_payout_enabled'] as num?)?.toInt(),
      signupMethod: json['signup_method'] as String?,
      deletedAt: json['deleted_at'],
      signupCustomFieldsResponses: json['signup_custom_fields_responses'],
      deletedBy: json['deleted_by'],
      refPhyCommissionLevel2:
          (json['ref_phy_commission_level_2'] as num?)?.toInt(),
      refPhyComL2ValueType: json['ref_phy_com_l2_value_type'] as String?,
      totalNotiCount: (json['total_noti_count'] as num?)?.toInt(),
      totalChatNotiCount: (json['total_chat_noti_count'] as num?)?.toInt(),
      aboutMe: json['about_me'],
      totalSell: json['total_sell'] as String?,
      sellerUniqueName: json['seller_unique_name'],
      globeLink: json['globe_link'],
      youtubeLink: json['youtube_link'],
      linkedinLink: json['linkedin_link'],
      facebookLink: json['facebook_link'],
      sellerTitle: json['seller_title'],
      coverPic: json['cover_pic'],
      affiliateCouponCode: json['affiliate_coupon_code'],
      affiliateCouponUuid: json['affiliate_coupon_uuid'],
      meta: json['meta'] == null
          ? null
          : Meta.fromJson(json['meta'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$UserImplToJson(_$UserImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'school_id': instance.schoolId,
      'can_write_doc': instance.canWriteDoc,
      'full_name': instance.fullName,
      'is_verified': instance.isVerified,
      'is_approved': instance.isApproved,
      'user_type': instance.userType,
      'created_at': instance.createdAt?.toIso8601String(),
      'is_private_chat': instance.isPrivateChat,
      'updated_at': instance.updatedAt?.toIso8601String(),
      'profile_pic': instance.profilePic,
      'is_online': instance.isOnline,
      'bio': instance.bio,
      'user_id': instance.userId,
      'social_auth_provider': instance.socialAuthProvider,
      'last_login': instance.lastLogin?.toIso8601String(),
      'status': instance.status,
      'is_suspended': instance.isSuspended,
      'pause_date': instance.pauseDate,
      'expire_date': instance.expireDate,
      'last_name': instance.lastName,
      'order_id': instance.orderId,
      'first_name': instance.firstName,
      'custom_fields': instance.customFields,
      'is_allow_chat': instance.isAllowChat,
      'ref_id': instance.refId,
      'ref_commission_level_1': instance.refCommissionLevel1,
      'ref_is_cookie_destroy_after_checkout':
          instance.refIsCookieDestroyAfterCheckout,
      'ref_commission_level_2': instance.refCommissionLevel2,
      'parent_ref_id': instance.parentRefId,
      'ref_com_l1_value_type': instance.refComL1ValueType,
      'ref_com_l2_value_type': instance.refComL2ValueType,
      'ref_allow_linked_membership': instance.refAllowLinkedMembership,
      'is_manual': instance.isManual,
      'referred_by': instance.referredBy,
      'is_eligible_for_special_offer': instance.isEligibleForSpecialOffer,
      'is_founding': instance.isFounding,
      'plan_id': instance.planId,
      'is_2fa_enabled': instance.is2faEnabled,
      'webpushsub': instance.webpushsub,
      'is_force_logout_enabled': instance.isForceLogoutEnabled,
      'payout_paypal_email': instance.payoutPaypalEmail,
      'ref_phy_commission_level_1': instance.refPhyCommissionLevel1,
      'is_manual_private_chat': instance.isManualPrivateChat,
      'ref_phy_com_l1_value_type': instance.refPhyComL1ValueType,
      'site_owner_user_id': instance.siteOwnerUserId,
      'ezy_affiliate_user_id': instance.ezyAffiliateUserId,
      'stripe_payout_enabled': instance.stripePayoutEnabled,
      'signup_method': instance.signupMethod,
      'deleted_at': instance.deletedAt,
      'signup_custom_fields_responses': instance.signupCustomFieldsResponses,
      'deleted_by': instance.deletedBy,
      'ref_phy_commission_level_2': instance.refPhyCommissionLevel2,
      'ref_phy_com_l2_value_type': instance.refPhyComL2ValueType,
      'total_noti_count': instance.totalNotiCount,
      'total_chat_noti_count': instance.totalChatNotiCount,
      'about_me': instance.aboutMe,
      'total_sell': instance.totalSell,
      'seller_unique_name': instance.sellerUniqueName,
      'globe_link': instance.globeLink,
      'youtube_link': instance.youtubeLink,
      'linkedin_link': instance.linkedinLink,
      'facebook_link': instance.facebookLink,
      'seller_title': instance.sellerTitle,
      'cover_pic': instance.coverPic,
      'affiliate_coupon_code': instance.affiliateCouponCode,
      'affiliate_coupon_uuid': instance.affiliateCouponUuid,
      'meta': instance.meta,
    };
